### ISSUE TITLE
[bug] Embedded notes doesn't get exported

### ISSUE THREAD

**Issue by rodrigo-rufino** [OliverBalfour/obsidian-pandoc#29]
This error happens when the embedded notes are not on the same folders as the main document.

Obsidian markdown document:
![Screenshot from 2021-05-17 11-24-17](https://user-images.githubusercontent.com/18670446/118504970-5d6a5780-b702-11eb-986b-1b233777a19a.png)

Exported .odt document:
![Screenshot from 2021-05-17 11-23-55](https://user-images.githubusercontent.com/18670446/118504975-5e9b8480-b702-11eb-8211-07521479b1d8.png)

**Comment by OliverBalfour** [comment]
Thanks for reporting this!

I'll try to fix this by the end of the month (super busy right now lol)

> when the embedded notes are not in the same folder as the main document.

Ahhh, that makes sense. I use a giant flat folder for my zettelkasten hence why I never spotted this

**Comment by OliverBalfour** [comment]
Fixed! If you have any issues please let me know.

Apologies it took so long too, I've been very busy as of late

**Comment by tim-hilde** [comment]
Thank you for your update! Unfortunately, block embeds like ![[verbeekMoralizingTechnologyUnderstanding2011#^f1a73f]] are still not working

**Comment by OliverBalfour** [comment]
Yes, sorry about that! That is still broken and will be fixed separately in #23.
